### ISSUE TITLE
Звуковое сопровождение 

### ISSUE THREAD

**Issue by tohkoecalo** [ADGuschin/CitadelofSevenSins#11]
Необходимо скачать и вставить в игру звуковые эффекты прыжков, подкатов, музыки меню, паузы, с экрана смерти убрать музыку уровня; инвертировать значок музыки

**Comment by PResurrection** [comment]
Звуковое сопровождение добавлено, закрываю задачу, добавлю другую для корректировки работы звукового сопровождения.
