### ISSUE TITLE
1 блок земельки 

### ISSUE THREAD

**Issue by tohkoecalo** [ADGuschin/CitadelofSevenSins#3]
48х25 блок земельки и при большом желании такую же коробочку, сверху у земли неровно, лучше завтра

**Comment by AlexandraKolomoitseva** [comment]
Блок земли будет на земле, или в воздухе, и блок подразумевает под собой строго прямоугольную форму? Что за коробочка, металлическая, картонная, мятая не мятая?

**Comment by tohkoecalo** [comment]
Земля на земле, а коробку Типо ящика, чтобы заменить нынешнюю, поэтому прямоугольную, да

**Comment by tohkoecalo** [comment]
![AlexandraZhidenko](Шура)

**Comment by tohkoecalo** [comment]
![Шура](AlexandraZhidenko)

**Comment by tohkoecalo** [comment]
Тестю
