### ISSUE TITLE
СРОЧНО НУЖНО ПОФИКСИТЬ

### ISSUE THREAD

**Issue by PResurrection** [ADGuschin/CitadelofSevenSins#36]
Попробую описать баг. Вызвать его достаточно легко: заходите в игру, жмете старт, играете, выходите в меню, снова жмете старт, можете попробовать понажимать кнопки управления(управления у вас не будет, звук действия проигрываться будет), а можете не нажимать, баг все равно будет.
Стоит заметить, что сначала мы столкнулись с этим багом во время проектирования туториала с Дониэлом, но тогда мы посчитали, что это не баг, а фича. Затем это как-то перенеслось и на основную игру. В ошибках там что-то пишет про хэндл_геометри_контакт и про переполнение буфера. Есть вероятность, что это как-то связано с векторами (просто пока работали с Донечом, он там че-то менял).
Такие дела
![image](https://user-images.githubusercontent.com/38156187/39522598-2784d70e-4e2c-11e8-992d-2f7bb44baa4d.png)
![image](https://user-images.githubusercontent.com/38156187/39522813-edc645ce-4e2c-11e8-93c7-5b62dddd35f8.png)

**Comment by Sabadon** [comment]
Ну переполнение буфера там со звуком, скорей всего он багает и пытаеться дохрена звуков воспроизвести или ченить такое
